export const CHECK_SESSION_VALID = 'CHECK_SESSION_VALID';
export const CHECK_SESSION_VALID_SUCCESS = 'CHECK_SESSION_VALID_SUCCESS';
export const CHECK_SESSION_VALID_FAIL = 'CHECK_SESSION_VALID_FAIL';
